"""Generate all figures needed for the thesis report.
Note: Uses joblib.load for loading scikit-learn models (trusted local files).
"""

import sys
sys.path.insert(0, '.')

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import roc_curve, precision_recall_curve, confusion_matrix
from sklearn.metrics import roc_auc_score, average_precision_score

# Setup
OUTPUT = Path('output/thesis_figures')
OUTPUT.mkdir(parents=True, exist_ok=True)
plt.rcParams['font.size'] = 11
plt.rcParams['figure.dpi'] = 150

# Load data
X_train = np.load('output/X_train.npy')
X_test = np.load('output/X_test.npy')
y_test = np.load('output/y_test.npy', allow_pickle=True)

from src.data_processing.feature_extractor import FEATURE_NAMES

# Load models (trusted local files generated by our pipeline)
import joblib
if_data = joblib.load('trained_models/isolation_forest.joblib')
lof_data = joblib.load('trained_models/lof.joblib')
svm_data = joblib.load('trained_models/ocsvm.joblib')
if_model = if_data['model']
lof_model = lof_data['model']
svm_model = svm_data['model']

y_true = (y_test == 'attack').astype(int)

# Figure 1: ROC Curves
fig, ax = plt.subplots(figsize=(8, 6))
for name, model, color in [
    ('Isolation Forest', if_model, '#2563EB'),
    ('LOF', lof_model, '#10B981'),
    ('One-Class SVM', svm_model, '#F59E0B'),
]:
    scores = -model.score_samples(X_test)
    fpr, tpr, _ = roc_curve(y_true, scores)
    auc = roc_auc_score(y_true, scores)
    ax.plot(fpr, tpr, color=color, linewidth=2, label=f'{name} (AUC={auc:.3f})')
ax.plot([0, 1], [0, 1], 'k--', alpha=0.3)
ax.set_xlabel('False Positive Rate')
ax.set_ylabel('True Positive Rate')
ax.set_title('ROC Curves - Model Comparison')
ax.legend(loc='lower right')
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig(OUTPUT / 'fig_roc_curves.png')
plt.close()
print('Generated: fig_roc_curves.png')

# Figure 2: Precision-Recall Curves
fig, ax = plt.subplots(figsize=(8, 6))
for name, model, color in [
    ('Isolation Forest', if_model, '#2563EB'),
    ('LOF', lof_model, '#10B981'),
    ('One-Class SVM', svm_model, '#F59E0B'),
]:
    scores = -model.score_samples(X_test)
    prec, rec, _ = precision_recall_curve(y_true, scores)
    ap = average_precision_score(y_true, scores)
    ax.plot(rec, prec, color=color, linewidth=2, label=f'{name} (AP={ap:.3f})')
ax.set_xlabel('Recall')
ax.set_ylabel('Precision')
ax.set_title('Precision-Recall Curves')
ax.legend(loc='lower left')
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig(OUTPUT / 'fig_pr_curves.png')
plt.close()
print('Generated: fig_pr_curves.png')

# Figure 3: Confusion Matrices
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
for i, (name, model) in enumerate([
    ('Isolation Forest', if_model),
    ('LOF', lof_model),
    ('One-Class SVM', svm_model),
]):
    preds = model.predict(X_test)
    y_pred = (preds == -1).astype(int)
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[i],
                xticklabels=['Normal', 'Attack'], yticklabels=['Normal', 'Attack'])
    axes[i].set_title(name)
    axes[i].set_xlabel('Predicted')
    axes[i].set_ylabel('Actual')
plt.suptitle('Confusion Matrices', fontsize=14)
plt.tight_layout()
plt.savefig(OUTPUT / 'fig_confusion_matrices.png')
plt.close()
print('Generated: fig_confusion_matrices.png')

# Figure 4: Feature Importance
importance = pd.read_csv('output/feature_importance.csv')
importance = importance.sort_values('Importance_Mean', ascending=True)
fig, ax = plt.subplots(figsize=(10, 6))
colors = ['#2563EB' if v > 0.01 else '#94A3B8' for v in importance['Importance_Mean']]
ax.barh(importance['Feature'], importance['Importance_Mean'] * 100, color=colors)
ax.set_xlabel('Importance (%)')
ax.set_title('Feature Importance Ranking (Isolation Forest)')
ax.grid(True, alpha=0.3, axis='x')
plt.tight_layout()
plt.savefig(OUTPUT / 'fig_feature_importance.png')
plt.close()
print('Generated: fig_feature_importance.png')

# Figure 5: Score Distribution
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
for i, (name, model) in enumerate([
    ('Isolation Forest', if_model),
    ('LOF', lof_model),
    ('One-Class SVM', svm_model),
]):
    scores = -model.score_samples(X_test)
    normal_scores = scores[y_true == 0]
    attack_scores = scores[y_true == 1]
    axes[i].hist(normal_scores, bins=50, alpha=0.6, label='Normal', color='#10B981', density=True)
    axes[i].hist(attack_scores, bins=50, alpha=0.6, label='Attack', color='#EF4444', density=True)
    axes[i].set_title(name)
    axes[i].set_xlabel('Anomaly Score')
    axes[i].legend()
plt.suptitle('Anomaly Score Distribution: Normal vs Attack', fontsize=14)
plt.tight_layout()
plt.savefig(OUTPUT / 'fig_score_distribution.png')
plt.close()
print('Generated: fig_score_distribution.png')

# Figure 6: Model Comparison Bar Chart
models_list = ['IF', 'LOF', 'OCSVM']
metrics = {
    'Accuracy': [0.8076, 0.8415, 0.8573],
    'F1-Score': [0.8863, 0.9045, 0.9131],
    'ROC-AUC': [0.8316, 0.9759, 0.9003],
}
x = np.arange(len(models_list))
width = 0.25
fig, ax = plt.subplots(figsize=(10, 6))
for i, (metric, values) in enumerate(metrics.items()):
    ax.bar(x + i*width, [v*100 for v in values], width, label=metric)
ax.set_ylabel('Score (%)')
ax.set_title('Model Performance Comparison')
ax.set_xticks(x + width)
ax.set_xticklabels(models_list)
ax.legend()
ax.set_ylim(70, 100)
ax.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.savefig(OUTPUT / 'fig_model_comparison_bar.png')
plt.close()
print('Generated: fig_model_comparison_bar.png')

# Figure 7: Feature Correlation Matrix
test_df = pd.DataFrame(X_test, columns=FEATURE_NAMES)
fig, ax = plt.subplots(figsize=(12, 10))
corr = test_df.corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='RdBu_r', center=0, ax=ax, square=True)
ax.set_title('Feature Correlation Matrix')
plt.tight_layout()
plt.savefig(OUTPUT / 'fig_correlation_matrix.png')
plt.close()
print('Generated: fig_correlation_matrix.png')

print(f'\nAll {len(list(OUTPUT.glob("*.png")))} figures saved to {OUTPUT}/')
